### ISSUE TITLE
Track duration not appearing in loaded Foobar playlist, even though present in xspf

### ISSUE THREAD

**Issue by jerryosity** [Chocobo1/foo_xspf_1#2]
I have duration checked for writing, and it appears with values in the generated xspf file. But when the xspf is loaded, the duration column for each track within Foobar shows up as a "?".  Clicking on the track for playback then shows the duration.   I don't see an option on the read settings for reading the duration.

[Using version 2.6.2 in Foobar2000 1.3.9]

**Comment by Chocobo1** [comment]
> the duration column for each track within Foobar shows up as a "?"

~~What is the data in <location>? as usual, can you post the xspf?~~ UPDATE: see next post.

> I don't see an option on the read settings for reading the duration.

This is intended. It is unreliable to match on duration (especially when passing xspf from one user to another user), for example, there might be 2 different files (each 1 on different users disk) that have different padding (or different silent at start/end) and yet they contain the same song.

**Comment by Chocobo1** [comment]
> the duration column for each track within Foobar shows up as a "?"

Intended again, I just think it's better for fb2k to figure out the actual track duration instead of relying on a value in playlist. Since in most condition user already have title, artist, album correctly displayed, that should be enough information (to the user), no?

**Comment by Chocobo1** [comment]
Despite what I said, try this version: [foo_xspf_1.zip](https://github.com/Chocobo1/foo_xspf_1/files/110823/foo_xspf_1.zip)

**Comment by jerryosity** [comment]
Mike,
    The duration now appears when loaded.  This works for me. Regarding 
the undesirability of relying on the duration value in the tracklist vs 
fb2k determining it directly from the track -- I agree with this point, 
generally, But in the specific use case of exporting/importing to change 
just the location, one naturally expects to see the revised playlist 
retain all the other previous info. Seeing question marks in the 
playlist for duration is usually indicative of a problem.
