### ISSUE TITLE
Avast (malware suspicion) - triggered

### ISSUE THREAD

**Issue by alectron** [Chocobo1/foo_xspf_1#3]
Heya, 
I just wanted to install this to try it if it would be suitable for generating xml files to feed to Traktor/Serato/Rekordbox from Foobar, but when installing, I get Avast to quarantine the .dll instantly with as suspected:
Win32:Evo-gen [Susp]
warning, when the .dll file of the .f2k-component gets extracted.
Potentially a false positive, but can be deterring/worrying to potential users.
Cheers.
c.

**Comment by Chocobo1** [comment]
Thanks, I submitted a false positive to avast.

BTW, I scan it with virus total: https://www.virustotal.com/zh-tw/file/b5182bd3693cafb6a0e6e2bdaad58b1300d1ddd1a271783170464e60d772b5d5/analysis/1454907229/
The results ain't clean :( and I never heard of `Rising` antivirus.

If you're still bothered about the detection, (luckily this is opensource project) you can either 1. read the code yourself. 2. get someone you trust to verify the code. Honestly, I don't know how to avoid these kind of problems and I don't care much about it. :P
